---
- name: loops
  hosts: localhost
  become: yes 
  tasks:
     - name: Create Users
       user: 
        name: "{{ item }}" 
        state: present
       with_items:
        - joe
        - george
        - ravi
        - mani

     - name: Get from multiple urls
       debug: var=item
       with_url:
         - "https://jsonplaceholder.typicode.com/posts/1"
         - "https://api.github.com/users/octocat"

     - name: View config files
       debug: var=item
       with_file:
          - "/etc/hosts"
          - "/etc/resolv.conf"

     - name: Check multiple mongodbs
       debug: 
            msg: "DB={{ item.database }} PID={{ item.pid }}"
       with_mongodb:
          - database: dev
            connection_string: "mongodb://dev.mongo/"
          - database: prod
            connection_string: "mongodb://prod.mongo/"
