-
  name: install tomcat and configure server
  hosts: localhost
  remote_user: root
  become: yes

  vars:
    path: /opt/tomcat

  tasks:
    - name: update package manager
      yum:
        name: '*'
        state: latest

    - name: install java
      command: amazon-linux-extras install java-openjdk11

    - name: Create tomcat user
      user:
        name: tomcat

    - name: Create tomcat group
      group:
        name: tomcat

    - name: Create tomcat directory
      file:
        path: "{{ path }}"
        owner: tomcat
        group: tomcat
        mode: 755
        state: directory

    - name: download and unzip tomcat
      unarchive:
        src: https://downloads.apache.org/tomcat/tomcat-9/v9.0.87/bin/apache-tomcat-9.0.87.tar.gz
        dest: "{{ path }}"
        remote_src: yes

    - name: start tomcat server
      command: sh '{{ path }}'/apache-tomcat-9.0.87/bin/startup.sh
